# Generated by Django 2.2 on 2019-08-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, unique=True, verbose_name='Название ')),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Имя')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Planet', verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Имя')),
                ('age', models.IntegerField(default=18, verbose_name='Возраст')),
                ('email', models.CharField(default='', max_length=256, verbose_name='Email')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Planet', verbose_name='Название')),
            ],
        ),
    ]
