# Generated by Django 2.2 on 2019-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190819_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.CharField(default='', max_length=256, verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='Replys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=0)),
                ('question', models.ManyToManyField(to='main.Questions')),
                ('recruit', models.ManyToManyField(to='main.Recruit')),
            ],
        ),
    ]
