# Generated by Django 2.2 on 2019-08-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190819_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replys',
            name='question',
        ),
        migrations.AddField(
            model_name='replys',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Questions'),
        ),
        migrations.RemoveField(
            model_name='replys',
            name='recruit',
        ),
        migrations.AddField(
            model_name='replys',
            name='recruit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Recruit'),
        ),
    ]
