# Generated by Django 2.2 on 2019-08-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190819_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sith'),
        ),
    ]
