# Generated by Django 2.2 on 2019-08-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_recruit_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sith',
            name='name',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='Имя ситха'),
        ),
    ]
